# --------------------------------------------
# Kubernetes Deployment for valaxy-rtp
# --------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: valaxy-rtp                      # Name of the Deployment
  namespace: valaxy                     # Namespace where the Deployment will be created

spec:
  replicas: 2                           # Number of pod replicas to maintain
  selector:
    matchLabels:
      app: valaxy-rtp                   # Label selector to match the pods managed by this Deployment

  template:
    metadata:
      labels:
        app: valaxy-rtp                 # Labels assigned to the pods

    spec:
      # Image Pull Secrets for Private Registry
      imagePullSecrets:
      - name: jfrogcred                 # Secret to pull images from a private Docker registry (JFrog)

      containers:
      - name: valaxy-rtp                # Container name
        image: saidemy.jfrog.io/valaxy-docker/ttrend:2.1.2  # Docker image from JFrog with version 2.1.2
        imagePullPolicy: Always         # Always pull the latest image

        ports:
        - containerPort: 8000           # Container port exposed by this container

        env:                            # Environment variables for the application
        - name: CONSUMER_KEY            # Consumer key for the application
          value: "G6lmKhsi0V9TvXt6oKTfjRBCr"
        - name: CONSUMER_SECRET         # Consumer secret for the application
          value: "bEyDk8X0p8SQd4376eoNV4nH8To22sHcJOoFt0ZqOKS37hhI4q"
        - name: ACCESS_TOKEN            # Access token for the application
          value: "9703354-52rXHD6EeOQeYyhtNz1w8UVOgbcLcgOo4O7MB6WV3"
        - name: ACCESS_TOKEN_SECRET     # Access token secret for the application
          value: "zBThlZDEp8qnu7NwwdHNth8eg3Rf9zqbvUEFUTaZtN2SF"

