# --------------------------------------------
# Kubernetes Secret for JFrog Docker Registry
# --------------------------------------------

apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred                      # Name of the Secret
  namespace: valaxy                    # Namespace where the Secret will be created

data:
  # Base64 encoded Docker configuration
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJzYWlkZW15Lmpmcm9nLmlvIjogewoJCQkiYXV0aCI6ICJaRzlqYTJWeVkzSmxaRHBUWVdsa1pXMTVhWFJBTVRJeiIKCQl9Cgl9Cn0=

type: kubernetes.io/dockerconfigjson   # Secret type for Docker credentials
